### PR TITLE
Add ESPResSo easyconfig template with `software-commit`

### PR DESCRIPTION
**Pull request by Neves-P**
This adds a template easyconfig file and associated easystack file to build `ESPReSso` given a specific commit hash. In the easystackfile this hash is specified as an option `software-commit`.

I put the easystack in a subdirectory inside the `espresso` directory, but this can be moved somewhere else if that's better.

### CODE REVIEW

**Comment by ocaisa** [comment]
Anything that works is good for me, we may want to add a directory that gets searched automatically for additional easyconfigs (`EASYBUILD_ROBOT=/path/to/devel/easyconfigs`)

**Comment by Neves-P** [comment]
That's a good idea, it'll probably come in handy for installing new dependencies.

One other thing I just realised is that we may want to think about a naming convention for the easyconfigs. In this case we are building 4.2.2, but if we were to build from what's in main it would be something like 4.3-dev, so maybe we want to reflect that in the file name. On the other hand, we could remove the version number entirely since the commit is what matters. If this has no other implications then maybe it should be left for the developers to decide.

**Comment by Neves-P** [comment]
Build works locally for this commit 👍

**Comment by boegel** [comment]
Filename doesn't matter much for this experiment, looks good to me.

Next steps are:
i) setting up the bot for EESSI (with the changes implemented in https://github.com/EESSI/eessi-bot-software-layer/pull/283 active);
ii) working on the bot build job script to figure out how this can be picked up to actually build something and produce a tarball for it;

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by boegel** [comment]
bot: build

**Comment by boegel** [comment]
bot: build

**Comment by boegel** [comment]
bot: build

**Comment by boegel** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by Neves-P** [comment]
bot: build

**Comment by boegel** [comment]
@Neves-P As discussed, we should try and get those builds done under a `test` project, adding an extra level to the directory hierarchy?

**Comment by Neves-P** [comment]
> @Neves-P As discussed, we should try and get those builds done under a `test` project, adding an extra level to the directory hierarchy?

Agreed! I will merge this PR since we just ingested the installation as is, which we can then manually remove from the s0.

1st one is done! 🥳

**Pull request merged**
